import {
  BookKey,
  Calendar,
  CalendarOff,
  CircleHelp,
  CircleUser,
  HandCoins,
  LayoutDashboard,
  Package,
  Settings,
  SquareLibrary,
  UsersIcon,
} from "lucide-react";

export const menu = [
  {
    name: "Dashboard",
    path: "/",
    icon: LayoutDashboard,
    module: "dashboard",
    access: ["admin", "moderator", "user", "former"],
  },
  {
    name: "Employees",
    path: "/employees",
    icon: UsersIcon,
    module: "employee",
    access: ["admin", "moderator"],
  },
  {
    name: "Payroll",
    path: "/payroll",
    icon: HandCoins,
    module: "payroll",
    access: ["admin"],
  },
  {
    name: "Tools",
    path: "/tools",
    icon: Package,
    module: "tool",
    access: ["admin", "moderator"],
  },
  {
    name: "Courses",
    path: "/courses",
    icon: BookKey,
    module: "course",
    access: ["admin", "moderator"],
  },
  {
    name: "Assets",
    path: "/assets",
    icon: SquareLibrary,
    module: "asset",
    access: ["admin", "moderator"],
  },
  {
    name: "Leaves",
    path: "/leaves",
    icon: CalendarOff,
    module: "leave",
    access: ["admin", "moderator"],
  },
  {
    name: "Leave Requests",
    path: "/leave-requests",
    icon: CircleHelp,
    module: "leave",
    access: ["admin", "moderator"],
  },
  {
    name: "My Profile",
    path: "/my-profile",
    icon: CircleUser,
    module: "employee",
    access: ["user", "former"],
  },
  {
    name: "My Leaves",
    path: "/my-leaves",
    icon: CalendarOff,
    module: "leave",
    access: ["user", "former"],
  },
  {
    name: "My Leave Requests",
    path: "/my-leave-requests",
    icon: CircleHelp,
    module: "leave",
    access: ["user", "former"],
  },
  {
    name: "Calendar",
    path: "/calendar",
    icon: Calendar,
    module: "calendar",
    access: ["admin", "moderator", "user"],
  },
  {
    name: "Settings",
    path: "/settings",
    icon: Settings,
    module: "setting",
    access: ["admin"],
  },
];
